### ISSUE TITLE
Json import does not create checklists

### ISSUE THREAD

**Issue by TerrorSource** [nicolonsky/ModernWorkplaceConcierge#16]
Hi,

Thanks for the Tool! Saves a lot of work typing it over in Planner.

However, when doing an import of Trello JSON file, there are no Checklists created within the task.
I cannot attach the JSON due to privacy issues.

How do i solve this?

**Comment by nicolonsky** [comment]
Added this functionality on the 28. December: https://github.com/nicolonsky/ModernWorkplaceConcierge/commit/e8c98956d067ee641f67ed54e26d244d3fa762e4.
Have you tested it again since then? If using a self hosted instance make sure to trigger an update.

**Comment by TerrorSource** [comment]
Just tried it about 15 minutes ago. No self-hosted instance.

**Comment by nicolonsky** [comment]
@TerrorSource redeployed the latest commit and tested it with a task containing a trello checklist which got imported successfully:
![Planner_checklist](https://user-images.githubusercontent.com/32899754/71627394-739d7380-2bf2-11ea-907f-623d9f850260.png)
![Trello_checklist](https://user-images.githubusercontent.com/32899754/71627395-739d7380-2bf2-11ea-8c28-dda9645254b5.png)

If you still experience issues after testing you might want to compare your json export against mine: [kcOz0mcM.zip](https://github.com/nicolonsky/ModernWorkplaceConcierge/files/4013069/kcOz0mcM.zip)

**Comment by nicolonsky** [comment]
Closing because received feedback from other users with successful imports & added checklist improvements to the latest release
