### ISSUE TITLE
Unable to Export Conditional Access Policies

### ISSUE THREAD

**Issue by Rippsy** [nicolonsky/ModernWorkplaceConcierge#30]
Hi Nicola,

I've previously used this tool on our conditional access policies to take a backup before making changes, very useful :)

However when running the Export I now get an error, which also disappears off screen before I can copy and paste it.  I managed to take a screenshot; ![export-cas](https://user-images.githubusercontent.com/61187350/74729193-f4b0d880-523b-11ea-83e2-6811e69fccfd.png)

**Comment by nicolonsky** [comment]
Thanks should be fixed in: [https://github.com/nicolonsky/ModernWorkplaceConcierge/commit/efa4de1408b7be03a3dcb5d24fde4f629aa3495c](https://github.com/nicolonsky/ModernWorkplaceConcierge/commit/efa4de1408b7be03a3dcb5d24fde4f629aa3495c)
