### ISSUE TITLE
Login problem after first wrong login

### ISSUE THREAD

**Issue by Rohoff** [nicolonsky/ModernWorkplaceConcierge#31]
At the first login I missed to check the box "alow for all" or someting like that and so I can't choose a plan from other users. I allready deleted within O365 the access to the app but login is still possible w/o a new request. What can I do?

**Comment by nicolonsky** [comment]
You will only see the plans your user has access to because the app works with delegated permissions. Removing the app needs to happen in Azure AD, by deleting the enterprise app. Nevertheless you haven't done anything wrong, you just need to add your user to the desired planner plans to perform imports.

**Comment by Rohoff** [comment]
Cool – thanks!
I will try and let you know!

Regards,
Marco



Von: Nicola Suter <notifications@github.com>
Gesendet: Samstag, 29. Februar 2020 09:26
An: nicolonsky/ModernWorkplaceConcierge <ModernWorkplaceConcierge@noreply.github.com>
Cc: Rohoff, Marco <Marco.Rohoff@treif.com>; Author <author@noreply.github.com>
Betreff: Re: [nicolonsky/ModernWorkplaceConcierge] Login problem after first wrong login (#31)


You will only see the plans your user has access to because the app works with delegated permissions. Removing the app needs to happen in Azure AD, by deleting the enterprise app. Nevertheless you haven't done anything wrong, you just need to add your user to the desired planner plans to perform imports.

**Comment by Rohoff** [comment]
All wonderful – great tool! Thanks a lot!
Regards,
Marco


Von: Rohoff, Marco
Gesendet: Montag, 2. März 2020 08:29
An: 'nicolonsky/ModernWorkplaceConcierge' <reply@reply.github.com>; nicolonsky/ModernWorkplaceConcierge <ModernWorkplaceConcierge@noreply.github.com>
Cc: Author <author@noreply.github.com>
Betreff: AW: [nicolonsky/ModernWorkplaceConcierge] Login problem after first wrong login (#31)

Cool – thanks!
I will try and let you know!

Regards,
Marco



Von: Nicola Suter <notifications@github.com<mailto:notifications@github.com>>
Gesendet: Samstag, 29. Februar 2020 09:26
An: nicolonsky/ModernWorkplaceConcierge <ModernWorkplaceConcierge@noreply.github.com<mailto:ModernWorkplaceConcierge@noreply.github.com>>
Cc: Rohoff, Marco <Marco.Rohoff@treif.com<mailto:Marco.Rohoff@treif.com>>; Author <author@noreply.github.com<mailto:author@noreply.github.com>>
Betreff: Re: [nicolonsky/ModernWorkplaceConcierge] Login problem after first wrong login (#31)


You will only see the plans your user has access to because the app works with delegated permissions. Removing the app needs to happen in Azure AD, by deleting the enterprise app. Nevertheless you haven't done anything wrong, you just need to add your user to the desired planner plans to perform imports.

**Comment by Rohoff** [comment]
All is working fine! Thanks for the hint!
