### ISSUE TITLE
Trello Import not completed?

### ISSUE THREAD

**Issue by MaxDiOrio** [nicolonsky/ModernWorkplaceConcierge#32]
Hi!

I'm using your online version, and it imported all the tasks, but the import has been running for about 10 minutes now (spinning import icon), and items like checklists are not showing up.  Labels aren't showing up - although you don't specify if they should migrate.

**Comment by nicolonsky** [comment]
Items not specified in the docs won't be migrated. Whereas checklists should be successfully migrated. Did you see any error messages on the status bar (you can expand it)?

**Comment by MaxDiOrio** [comment]
Absolutely nothing.  It just sits there and spins.  Only thing in the status bar was the connection successful.

**Comment by nicolonsky** [comment]
Is there a chance that your trello export is malformed? I just ran a short test and everything works as expected. 
![image](https://user-images.githubusercontent.com/32899754/77114610-182e9500-6a2d-11ea-8bdf-237e9f8e82e1.png)

**Comment by MaxDiOrio** [comment]
The same export was used in another import app without issue.

________________________________

**Comment by nicolonsky** [comment]
Could you provide me your export if it not contains any sensitive information? Would appreciate that so I can improve the tool.


On 19 Mar 2020, at 22:03, Max DiOrio <notifications@github.com> wrote:

﻿

The same export was used in another import app without issue.

________________________________
