### ISSUE TITLE
Auto deployment failed

### ISSUE THREAD

**Issue by pbjorklund** [nicolonsky/ModernWorkplaceConcierge#37]
Command: "D:\home\site\deployments\tools\deploy.cmd"
Handling .NET Web Application deployment.
MSBuild auto-detection: using msbuild version '14.0.23107.0 built by: D14REL' from 'D:\Program Files (x86)\MSBuild\14.0\Bin'.
All packages listed in packages.config are already installed.
D:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets(242,5): warning : No compiler log specified, 'Clean' won't work. [D:\home\site\repository\ModernWorkplaceConcierge\ModernWorkplaceConcierge.csproj]
Helpers\AzureADIDCache.cs(36,52): error CS1003: Syntax error, ',' expected [D:\home\site\repository\ModernWorkplaceConcierge\ModernWorkplaceConcierge.csproj]
Helpers\AzureADIDCache.cs(64,53): error CS1003: Syntax error, ',' expected [D:\home\site\repository\ModernWorkplaceConcierge\ModernWorkplaceConcierge.csproj]
Helpers\AzureADIDCache.cs(98,52): error CS1003: Syntax error, ',' expected [D:\home\site\repository\ModernWorkplaceConcierge\ModernWorkplaceConcierge.csproj]
Helpers\AzureADIDCache.cs(122,56): error CS1003: Syntax error, ',' expected [D:\home\site\repository\ModernWorkplaceConcierge\ModernWorkplaceConcierge.csproj]
Helpers\AzureADIDCache.cs(147,59): error CS1003: Syntax error, ',' expected [D:\home\site\repository\ModernWorkplaceConcierge\ModernWorkplaceConcierge.csproj]
Helpers\AzureADIDCache.cs(155,104): error CS1525: Invalid expression term 'string' [D:\home\site\repository\ModernWorkplaceConcierge\ModernWorkplaceConcierge.csproj]
Helpers\AzureADIDCache.cs(155,111): error CS1003: Syntax error, ',' expected [D:\home\site\repository\ModernWorkplaceConcierge\ModernWorkplaceConcierge.csproj]
Failed exitCode=1, command="D:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" "D:\home\site\repository\ModernWorkplaceConcierge\ModernWorkplaceConcierge.csproj" /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="D:\local\Temp\8d7e904ffdc1a5b";AutoParameterizationWebConfigConnectionStrings=false;Configuration=Release;UseSharedCompilation=false /p:SolutionDir="D:\home\site\repository\.\\"
An error has occurred during web site deployment.
\r\nD:\Program Files (x86)\SiteExtensions\Kudu\86.20224.4450\bin\Scripts\starter.cmd "D:\home\site\deployments\tools\deploy.cmd"

**Comment by nicolonsky** [comment]
Deployment script fails because the following setting needs to be present on the app service:
```
 {
    "name": "MSBUILD_PATH",
    "value": "%MSBUILD_15_DIR%\\msbuild.exe",
    "slotSetting": false
  }
```

-> Will update the arm template with this one

**Comment by nicolonsky** [comment]
Fixed in: https://github.com/nicolonsky/ModernWorkplaceConcierge/commit/e14c9928ca5afc65082209bf846753a5c67c9627. Will be merged to master with next PR. Thanks for reporting @pbjorklund
