### ISSUE TITLE
Feature request: Trello Import - User mapping

### ISSUE THREAD

**Issue by pbjorklund** [nicolonsky/ModernWorkplaceConcierge#38]
Having a mapping section where you can select which trello users map to which O365 user would be super.

**Comment by nicolonsky** [comment]
This is already possible by editing the exported json file from trello. Simply modify the ```fullName``` property in the ```"members": []``` to match the display name of your desired Office 365 Account:
![image](https://user-images.githubusercontent.com/32899754/80306207-1b523900-87c2-11ea-80f2-8e869e8a9b01.png)

Will add this to the docs!

**Comment by nicolonsky** [comment]
Added to documentation https://github.com/nicolonsky/ModernWorkplaceConcierge/wiki/Migrate-trello-tasks-to-Microsoft-Planner#mapping-trello-accounts-to-office-365-users
