### ISSUE TITLE
Unknown Error code

### ISSUE THREAD

**Issue by fperoux** [nicolonsky/ModernWorkplaceConcierge#47]
Hello,

If a user do not have the right to access the intune service, the error message is not descriptive/user friendly (see screenshot attached).

![MWC_ErrorScreen_NoAccess](https://user-images.githubusercontent.com/27715088/83155357-25bc6700-a0cf-11ea-8ba7-e2a2d1bdfe62.png)

Do you think it would be possible to include an error message page stating the user do not have access to Intune service for example.

Thank you!

**Comment by nicolonsky** [comment]
Added proper error handling for the intune actions which catch the respective exception although the exception text is not very convenient. But I think the forbidden status should be sufficient @fperoux ?
![image](https://user-images.githubusercontent.com/32899754/87938957-995b6e80-ca97-11ea-8011-d0856d0d49d3.png)
