### ISSUE TITLE
Target Office Group Drowndown

### ISSUE THREAD

**Issue by chrispaivacwb** [nicolonsky/ModernWorkplaceConcierge#48]
Target Office 365 Planner Plan dropdown field only shows 7 options.
I got more than 20 Planner Plans.
Is this a limitation ?

**Comment by nicolonsky** [comment]
It only shows planner plans the signed-in user has access to. So is your user a member of the Office 365 Groups / Plan which you‘re missing?

**Comment by chrispaivacwb** [comment]
Yes, he is the owner of his O365 group.

[Image 01](https://farmaciarovalbr-my.sharepoint.com/:i:/g/personal/christian_paiva_farmaciaroval_com_br/EX5dahocO6xEjic3xcvZNHgBU_Z_MMQg1SYM4x0MShdfZw?e=NtJoTY)

[Image 02](https://farmaciarovalbr-my.sharepoint.com/:i:/g/personal/christian_paiva_farmaciaroval_com_br/EVakMysbjOZFhAvUlqrfY7UBLX5gN3y70saP3qjdwoCQXw?e=4cSSIZ)

**Comment by nicolonsky** [comment]
Tried to repro your issue, I have no issues seeing more than 7 plans. BUT what's really strange is that there are only plans visible you have visited at least once with that user. Seems this limitation comes with the Microsoft Graph API. Would be interesting if that helps you as well?

**Comment by nicolonsky** [comment]
This is really related to Graph, also occurs with the Graph Explorer. You need to have visited each plan at least once (even if you created it): 
![image](https://user-images.githubusercontent.com/32899754/83680760-ab657880-a5e1-11ea-8bbb-36d29e56f586.png)

**Comment by chrispaivacwb** [comment]
Great !! After I visited the plan I could see them in the dropdown list. Thanks for your help and prompt response. By the way, great app and very handy. Thanks for your time coding and sharing.

**Comment by nicolonsky** [comment]
Added to documentation https://github.com/nicolonsky/ModernWorkplaceConcierge/wiki/Migrate-trello-tasks-to-Microsoft-Planner
