### ISSUE TITLE
Logs Download check box

### ISSUE THREAD

**Issue by redkaffe** [nicolonsky/ModernWorkplaceConcierge#53]
When doing testing i found myself many times wishing i had thought of cpying the logs before re-running the ttol, as those are not available afterwards. Maybe add a check box to force download of logs whenever an operation is done on the tool would help keeping tracks of previous runs.

**Comment by nicolonsky** [comment]
You have now a simple download button which downloads a text file with the operation results 
![image](https://user-images.githubusercontent.com/32899754/87981224-2ffa5080-cad5-11ea-8b71-7da25ddeb144.png)

I would not consider this as a real log file but it shows you basically all the Graph API requests which are performed.

Didn't implement an auto-download as in my opinion the user should decide whether he wants to download a file.
