### ISSUE TITLE
Assignement Recap function

### ISSUE THREAD

**Issue by redkaffe** [nicolonsky/ModernWorkplaceConcierge#54]
In a general approach to "not forget anything", would it be possible to have a separate log within the zip file that state for every resource if it was assigned to a group (and get that group name if possible), in a form that would allow quick repercution of assignement by the team importing the resources afterward?

**Comment by nicolonsky** [comment]
I have the following idea:

* Export assignments for all entities currently supported
* Generate a mapping file for imports which can be edited with "Old Azure AD Group ID" -> "New Azure AD Group ID"
     * On import the mapping file can be adjusted as needed to reference another Azure AD Group ID

Guess this would be suitable for most users and reduces manual tasks
