### ISSUE TITLE
Windows Domain Join Configuration Not Supported

### ISSUE THREAD

**Issue by robiwisc** [nicolonsky/ModernWorkplaceConcierge#55]
I tried importing Intune configurations using the individual JSON files and received the following error on a Domain Join Configuration profile.

_2020-07-15T15:31:05.800Z Error: Unsupported configuration type #microsoft.graph.windowsDomainJoinConfiguration_

The JSON file:

{
  "computerNameStaticPrefix": "HAADJ-",
  "computerNameSuffixRandomCharCount": 9,
  "activeDirectoryDomainName": "DOMAIN.com",
  "organizationalUnit": "OU=Autopilot,OU=Windows 10,OU=Computers,OU=Client Management,DC=DOMAIN,DC=com",
  "lastModifiedDateTime": "2020-07-14T21:45:29.8547531+00:00",
  "roleScopeTagIds": [
    "0"
  ],
  "supportsScopeTags": true,
  "createdDateTime": "2020-07-14T21:45:29.8547531+00:00",
  "displayName": "Template - Domain Join Profile",
  "version": 1,
  "id": "78ed40ae-3d23-4767-33e3-dcf2a84d33b0",
  "@odata.type": "#microsoft.graph.windowsDomainJoinConfiguration"
}

**Comment by nicolonsky** [comment]
Thanks for the feedback; should be fixed https://github.com/nicolonsky/ModernWorkplaceConcierge/commit/f6fac1d677aeb2c67665c186b4c24ea975b23e59
