### ISSUE TITLE
The reply URL specified in the request does not match the reply URLs configured

### ISSUE THREAD

**Issue by cccn714** [nicolonsky/ModernWorkplaceConcierge#74]
I have deployed a private instance in my tenant. I believe I followed your instructions from [here](https://github.com/nicolonsky/ModernWorkplaceConcierge/wiki/Self-hosting-a-custom-instance) correctly but I am getting the following error when I try and log in.

Message: AADSTS50011: The reply URL specified in the request does not match the reply URLs configured for the application: 'd2d4508b-ef28-4dec-8795-454020cb3414'.

Looks like a bad url, any help on where this setting would need to be fixed. I have checked all my urls and they appear to be ok.
Thanks

**Comment by nicolonsky** [comment]
@cccn714 you need to add the URL of your instance to the app registration as reply URL: ![](https://github.com/nicolonsky/ModernWorkplaceConcierge/raw/master/Doc/SelfHosting/AppServiceURL.png)
