### ISSUE TITLE
The request is invalid: A type named 'microsoft.taskServices.plannerAssignmentCollection' could not be resolved by the model.

### ISSUE THREAD

**Issue by zer777** [nicolonsky/ModernWorkplaceConcierge#75]
Hi,

I'm getting the following error when trying to import a JSON from Trello to Planner:

`2021-01-18T15:40:15.848Z Error: Message: The request is invalid: A type named 'microsoft.taskServices.plannerAssignmentCollection' could not be resolved by the model. When a model is available, each type name must resolve to a valid type. Inner error: AdditionalData: date: 2021-01-18T15:40:15 request-id: 309c5ccb-cdb0-4e44-8585-a36a461f24bf client-request-id: 309c5ccb-cdb0-4e44-8585-a36a461f24bf ClientRequestId: 309c5ccb-cdb0-4e44-8585-a36a461f24bf`

Also, I attached the log:
[ModernWorkplaceConcierge.log](https://github.com/nicolonsky/ModernWorkplaceConcierge/files/5831157/ModernWorkplaceConcierge.log)

Any clue for the cause of this issue?

Thanks

**Comment by developingkatie** [comment]
I'm also getting this, tested it a few weeks ago and it was fine but now is giving errors, looks like beta API its referencing has changed

**Comment by datrumole** [comment]
same, looks like we will need an update to get this tool back up and running

**Comment by r-moore88** [comment]
This is still an issue, would love to use this portion of the tool! Just migrated my team to O365,

**Comment by scottclausen** [comment]
We started receiving this error on a similar Planner Integration that had been working for weeks, resolved by setting the ODataType to null.

var plannerAssignments = new PlannerAssignments();
plannerAssignments.AddAssignee("325b79e7-3f3a-4d6a-8aa1-2affca7c358f");
**plannerAssignments.ODataType = null;**

**Comment by djswilly** [comment]
As others have commented recently, we have a solution that has been in production for more than a year and this issue has just appeared without any changes on our side. Would be good to know we can safely implement the workaround mentioned above without causing any future problems?

**Comment by emagdygithub** [comment]
> We started receiving this error on a similar Planner Integration that had been working for weeks, resolved by setting the ODataType to null.
> 
> var plannerAssignments = new PlannerAssignments();
> plannerAssignments.AddAssignee("325b79e7-3f3a-4d6a-8aa1-2affca7c358f");
> **plannerAssignments.ODataType = null;**

Thanks Scott this solved the same issue for me

**Comment by kdubious** [comment]
Solved an issue I had with adding Links:

```
details = new PlannerTaskDetails();
details.References = new PlannerExternalReferences();
details.References.ODataType = null; // <-- winner right here!
```
