### ISSUE TITLE
Import Planner Tasks

### ISSUE THREAD

**Issue by chrispaivacwb** [nicolonsky/ModernWorkplaceConcierge#76]
**I am getting this error and tasks are not imported.**
2021-02-04T16:59:35.058Z Error: Object reference not set to an instance of an object.

**Comment by LovenaC** [comment]
Hi @chrispaivacwb 

I can try if I can help. Is this happening after uploading the file and passing it to the controller ?

**Comment by chrispaivacwb** [comment]
I did a screen record showing import process and erros.
[Screen Record](https://farmaciarovalbr-my.sharepoint.com/:v:/g/personal/christian_paiva_farmaciaroval_com_br/Ebc9UY0_k-ZAoVN6sDiiJTsBNSvKqVz4OOZoAKR07iMyqA?e=cEVCih)

**Comment by tomten** [comment]
I get "Error: Object reference not set to an instance of an object" as well.

**Comment by RyanHecht** [comment]
+1 on this not working. It seems as though Trello lists get migrated to buckets just fine, but tasks aren't imported at all.

**Comment by nicolonsky** [comment]
Duplicate of https://github.com/nicolonsky/ModernWorkplaceConcierge/issues/75
