### ISSUE TITLE
Support for Endpoint security settings?

### ISSUE THREAD

**Issue by BlueToxic** [nicolonsky/ModernWorkplaceConcierge#79]
Are there any plans to add functionality for Endpoint security settings?
They currently don't seem to be part of the export.
https://docs.microsoft.com/en-us/mem/intune/protect/endpoint-security

**Comment by wombatzone** [comment]
Would love to see this.  We're supposed to be putting our security policies in this new  "workflow" called Endpoint Security and so now we're back to creating them manually in every tenant.

**Comment by Flo6488** [comment]
Is there a timeline or plans when you can export Endpoint Security -> AV/Defender Policies etc.?
That would be very helpful. Currently there is no possibility to export this. So now we're back to creating them manually in every tenant.
