### ISSUE TITLE
Azure Deployment - Cannot find SourceControlToken with name GitHub

### ISSUE THREAD

**Issue by roberthoebel** [nicolonsky/ModernWorkplaceConcierge#88]
Hello,

when I try to deploy, i receive the following error:

`{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "message": "Cannot find SourceControlToken with name GitHub."
    }
  ]
}`

Thanks in advance,

Robert

**Comment by krazy-glue** [comment]
same here

**Comment by krazy-glue** [comment]
I found the solution,

when in the deployment in azure the RepoURL, must not include /tree/master in the URL.
as the branch is specified in the parameter below.

and I created a pull request to update this

**Comment by nicolonsky** [comment]
https://github.com/nicolonsky/ModernWorkplaceConcierge/pull/89
